#!/bin/bash
count="0"
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

if [[ ! -e ./mid3v2 ]] && [[ ! -e /usr/bin/mid3v2 ]]; then
	echo "ERROR: mid3v2 not found!"
	echo "Put the script in the same directory as this script,"
	echo "or install the whole package (python-mutagen for Ubuntu 10.04+,"
	echo "mid3v2 otherwise)."
	exit 1
elif [[ -e ./mid3v2 ]]; then
	sanitize() { 
		./mid3v2 "$@"
	}
elif [[ -e "/usr/bin/mid3v2" ]]; then
	sanitize() {
		mid3v2 "$@"
	}
elif [[ -e "/usr/bin/id3v2" ]]; then
	sanitize() {
		/usr/bin/id3v2
	}
fi

if [[ $1 == "-a" ]]; then
	printf '\033c'	
	for f in $(ls *.mp3); do
		echo "Sanitizing \"$f\""		
		sanitize --delete-frames=POPM "$f"
		count=$((count+1))
	done
	echo -e "\nSuccessfully sanitized $count MP3 files."
	exit 0
elif [[ $1 == "-d" ]]; then
	printf '\033c'
	for d in $(ls -d *); do
		echo "Going into directory $d"
		cd "$d"
		cnt=`ls -1 *.mp3 2>/dev/null | wc -l`
		if [ $cnt == "0" ]; then
			if [[ -d * ]]; then
				for dd in $(ls -d *); do
					echo -e "\nGoing into subdirectory $dd"
					echo -e "-------------------------------------------\n"
					cd "$dd"
					for f in $(ls *.mp3); do
						echo "Sanitizing \"$f\""		
						sanitize --delete-frames=POPM "$f"
						count=$((count+1))
					done
				done
				cd ../
			fi
		else
			echo -e "-------------------------------------------\n"
			for f in $(ls *.mp3); do
				echo "Sanitizing \"$f\""
				sanitize --delete-frames=POPM "$f"
				count=$((count+1))
			done
		fi
		cd ../
		echo ""
	done

	echo "Successfully sanitized $count MP3 files."
	exit 0
elif [[ $1 == "-f" ]]; then
	echo "Sanitizing \"$1\""
	sanitize --delete-frames=POPM $1
	echo "Done."
elif [[ $1 == "-p" ]]; then
	echo "Deleting mpxv1.mpd"
	rm -f $(find . -print | grep -i 'mpxv1.mpd')

	echo "Deleting harvesterdb.dat"
	rm -f $(find . -print | grep -i 'harvesterdb.dat')

	echo -e "\nNokia Music Player database purged successfully."
	exit 0
elif [[ $1 == "-h" ]] || [[ ! $1 ]]; then
	echo -e "\nNokia Music Sanitizer"
	echo "Sanitizes MP3 files for compatibility with non-POPM"
	echo "compliant music players on phones such as the E71."

	echo -e "\nUsage:"
	echo -e "\t -d        \t Sanitize all MP3 files in current directory."
	echo -e "\t -f <file> \t Sanitize <file>."
	echo -e "\t -h        \t Display this help message."
	echo -e "\t -p        \t Purge the music player database in your phone's"
	echo -e "\t           \t directory.\n"
fi

unset -v count
IFS=$SAVEIFS
exit 0
